debug: true
  
logging: 
  level:
    org.springframework.security: DEBUG

security:
  ignored: /favicon.ico,/js/**,/css/**
  oauth2:
    client:
      clientId: acme
      clientSecret: acmesecret
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize    
    resource:
      userInfoUri: http://localhost:9999/uaa/user

      
security.basic.enabled: false
spring.thymeleaf.cache: false

spring.datasource.url: jdbc:mysql://localhost/test
spring.datasource.username: root
spring.datasource.password: admin
spring.datasource.driver-class-name: com.mysql.jdbc.Driver